# Generated by Django 3.0.7 on 2020-07-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0003_auto_20200723_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
