# Generated by Django 3.0.7 on 2020-09-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200916_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
